<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.fRn_RlV' shared service.

return $this->privates['service_locator.fRn_RlV'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('confession' => function (): ?\App\Repository\ConfessionRepository {
    return ($this->privates['App\Repository\ConfessionRepository'] ?? $this->load('getConfessionRepositoryService.php'));
}));
