<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCzAab1S\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCzAab1S/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCzAab1S.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCzAab1S\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCzAab1S\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CzAab1S',
    'container.build_id' => '501201da',
    'container.build_time' => 1527849768,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCzAab1S');
