<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWlMHfFd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWlMHfFd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWlMHfFd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWlMHfFd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWlMHfFd\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WlMHfFd',
    'container.build_id' => 'd19c9414',
    'container.build_time' => 1527553032,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWlMHfFd');
